name: Build and Deploy CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: Use Node.js 12
          uses: actions/setup-node@v1
          with:
              node-version: '12.x'
        - run: npm install -g firebase-tools yarn
        - run: yarn install
        - run: yarn build
          env:
            GA_TRACKING_ID: ${{ secrets.GA_TRACKING_ID }}
        - run: aws s3 sync public/ s3://besidereal.com --no-guess-mime-type --delete
          env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_DEFAULT_REGION: "us-east-1"
