name: Build and Deploy CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: Use Node.js 12
          uses: actions/setup-node@v1
          with:
              node-version: '12.x'
        - run: npm install -g firebase-tools yarn
        - run: yarn install
        - run: yarn build
          env:
            GOOGLE_ANALYTICS_ID: ${{ secrets.GOOGLE_ANALYTICS_ID }}
        - run: firebase deploy --project porfolio-32f3b --token ${{ secrets.FIREBASE_TOKEN }}