name: Build and Deploy CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: Use Node.js 16
          uses: actions/setup-node@v2
          with:
              node-version: '16.x'
        - run: npm i
        - run: npm run build
          env:
            GA_TRACKING_ID: ${{ secrets.GA_TRACKING_ID }}
        - run: aws s3 sync public/ s3://besidereal.com --delete
          env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_DEFAULT_REGION: "us-east-1"
